/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlastRadiusConfig {
  'autoRollback' : boolean,
  'trafficPercentage' : bigint,
  'instancePercentage' : bigint,
  'maxDurationSeconds' : bigint,
  'geographicScope' : { 'multi' : null } |
    { 'global' : null } |
    { 'single' : null },
}
export interface DateRangeFilter {
  'toTs' : [] | [Timestamp],
  'fromTs' : [] | [Timestamp],
}
export interface ExecutionRunView {
  'id' : RunId,
  'status' : RunStatus,
  'completedAt' : [] | [Timestamp],
  'faultResults' : Array<FaultResultView>,
  'startedAt' : [] | [Timestamp],
  'metrics' : [] | [MetricsSnapshot],
  'experimentId' : ExperimentId,
  'actualDurationSeconds' : bigint,
  'resilienceScore' : [] | [bigint],
}
export type ExperimentId = bigint;
export interface ExperimentInput {
  'isTemplate' : boolean,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'hypothesis' : string,
  'infrastructureTarget' : InfrastructureTarget,
  'probes' : Array<ProbeConfig>,
  'blastRadius' : BlastRadiusConfig,
  'faults' : Array<FaultConfig>,
}
export type ExperimentStatus = { 'scheduled' : null } |
  { 'stopped' : null } |
  { 'completed' : null } |
  { 'error' : null } |
  { 'draft' : null } |
  { 'running' : null };
export interface ExperimentView {
  'id' : ExperimentId,
  'status' : ExperimentStatus,
  'isTemplate' : boolean,
  'owner' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'description' : string,
  'hypothesis' : string,
  'updatedAt' : Timestamp,
  'infrastructureTarget' : InfrastructureTarget,
  'probes' : Array<ProbeConfig>,
  'blastRadius' : BlastRadiusConfig,
  'faults' : Array<FaultConfig>,
}
export interface FailureMode {
  'occurrenceCount' : bigint,
  'faultType' : string,
  'averageSeverity' : bigint,
}
export interface FaultConfig {
  'id' : FaultId,
  'severityWeight' : bigint,
  'sequenceOrder' : bigint,
  'parameters' : Array<FaultParameter>,
  'durationSeconds' : bigint,
  'faultType' : string,
}
export type FaultId = bigint;
export interface FaultParameter { 'key' : string, 'value' : string }
export interface FaultResultView {
  'status' : FaultRunStatus,
  'completedAt' : [] | [Timestamp],
  'startedAt' : [] | [Timestamp],
  'affectedInstances' : bigint,
  'faultId' : FaultId,
}
export type FaultRunStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'executing' : null } |
  { 'failed' : null };
export interface InfraBreakdown {
  'runCount' : bigint,
  'infrastructure' : string,
  'averageScore' : bigint,
}
export type InfrastructureTarget = { 'aws' : null } |
  { 'azure' : null } |
  { 'custom' : null } |
  { 'kubernetes' : null } |
  { 'linux' : null };
export interface LogEntry {
  'id' : bigint,
  'result' : string,
  'affectedTarget' : string,
  'action' : string,
  'timestamp' : Timestamp,
  'experimentRunId' : RunId,
  'faultType' : string,
}
export interface MetricsSnapshot {
  'probeResults' : Array<ProbeResult>,
  'affectedServiceCount' : bigint,
  'cpuUtilization' : number,
  'errorRate' : number,
  'latencyP50' : number,
  'latencyP95' : number,
  'latencyP99' : number,
  'memoryUtilization' : number,
}
export interface OrganizationStats {
  'breakdownByService' : Array<ServiceBreakdown>,
  'breakdownByInfrastructure' : Array<InfraBreakdown>,
  'scoreHistory' : Array<ScoreHistoryEntry>,
  'currentScore' : bigint,
  'topFailureModes' : Array<FailureMode>,
}
export interface ProbeConfig {
  'id' : bigint,
  'name' : string,
  'probeType' : ProbeType,
}
export interface ProbeResult {
  'probeName' : string,
  'message' : string,
  'checkedAt' : Timestamp,
  'passed' : boolean,
  'probeId' : bigint,
}
export type ProbeType = {
    'metricThreshold' : {
      'threshold' : number,
      'operator' : string,
      'metricName' : string,
    }
  } |
  { 'custom' : { 'description' : string, 'command' : string } } |
  {
    'http' : {
      'url' : string,
      'expectedStatusCode' : bigint,
      'timeoutSeconds' : bigint,
    }
  };
export interface RecentRunSummary {
  'status' : string,
  'experimentId' : ExperimentId,
  'date' : Timestamp,
  'score' : [] | [bigint],
  'faultCount' : bigint,
  'probePassRate' : number,
  'runId' : RunId,
  'experimentName' : string,
}
export type RunId = bigint;
export type RunStatus = { 'stopped' : null } |
  { 'completed' : null } |
  { 'error' : null } |
  { 'queued' : null } |
  { 'running' : null };
export interface ScoreHistoryEntry {
  'score' : bigint,
  'timestamp' : Timestamp,
  'runId' : RunId,
}
export interface ServiceBreakdown {
  'service' : string,
  'failureCount' : bigint,
  'averageScore' : bigint,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addLogEntry' : ActorMethod<
    [RunId, string, string, string, string],
    LogEntry
  >,
  'cloneExperiment' : ActorMethod<[ExperimentId], [] | [ExperimentView]>,
  'completeRun' : ActorMethod<[RunId, MetricsSnapshot], boolean>,
  'createExperiment' : ActorMethod<[ExperimentInput], ExperimentView>,
  'deleteExperiment' : ActorMethod<[ExperimentId], boolean>,
  'emergencyStop' : ActorMethod<[RunId], boolean>,
  'filterRuns' : ActorMethod<
    [DateRangeFilter, [] | [string], [] | [string]],
    Array<RecentRunSummary>
  >,
  'getExecutionRun' : ActorMethod<[RunId], [] | [ExecutionRunView]>,
  'getExperiment' : ActorMethod<[ExperimentId], [] | [ExperimentView]>,
  'getOrganizationStats' : ActorMethod<[], OrganizationStats>,
  'getRecentRuns' : ActorMethod<[bigint], Array<RecentRunSummary>>,
  'getRunLogs' : ActorMethod<[RunId], Array<LogEntry>>,
  'getTopFailureModes' : ActorMethod<[], Array<FailureMode>>,
  'listExperiments' : ActorMethod<[], Array<ExperimentView>>,
  'listRunsByExperiment' : ActorMethod<[ExperimentId], Array<ExecutionRunView>>,
  'listTemplates' : ActorMethod<[], Array<ExperimentView>>,
  'startExperiment' : ActorMethod<[ExperimentId], [] | [ExecutionRunView]>,
  'updateExperiment' : ActorMethod<[ExperimentId, ExperimentInput], boolean>,
  'updateFaultResult' : ActorMethod<
    [RunId, FaultId, FaultRunStatus, bigint],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];