/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RunId = IDL.Nat;
export const Timestamp = IDL.Int;
export const LogEntry = IDL.Record({
  'id' : IDL.Nat,
  'result' : IDL.Text,
  'affectedTarget' : IDL.Text,
  'action' : IDL.Text,
  'timestamp' : Timestamp,
  'experimentRunId' : RunId,
  'faultType' : IDL.Text,
});
export const ExperimentId = IDL.Nat;
export const ExperimentStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'stopped' : IDL.Null,
  'completed' : IDL.Null,
  'error' : IDL.Null,
  'draft' : IDL.Null,
  'running' : IDL.Null,
});
export const InfrastructureTarget = IDL.Variant({
  'aws' : IDL.Null,
  'azure' : IDL.Null,
  'custom' : IDL.Null,
  'kubernetes' : IDL.Null,
  'linux' : IDL.Null,
});
export const ProbeType = IDL.Variant({
  'metricThreshold' : IDL.Record({
    'threshold' : IDL.Float64,
    'operator' : IDL.Text,
    'metricName' : IDL.Text,
  }),
  'custom' : IDL.Record({ 'description' : IDL.Text, 'command' : IDL.Text }),
  'http' : IDL.Record({
    'url' : IDL.Text,
    'expectedStatusCode' : IDL.Nat,
    'timeoutSeconds' : IDL.Nat,
  }),
});
export const ProbeConfig = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'probeType' : ProbeType,
});
export const BlastRadiusConfig = IDL.Record({
  'autoRollback' : IDL.Bool,
  'trafficPercentage' : IDL.Nat,
  'instancePercentage' : IDL.Nat,
  'maxDurationSeconds' : IDL.Nat,
  'geographicScope' : IDL.Variant({
    'multi' : IDL.Null,
    'global' : IDL.Null,
    'single' : IDL.Null,
  }),
});
export const FaultId = IDL.Nat;
export const FaultParameter = IDL.Record({
  'key' : IDL.Text,
  'value' : IDL.Text,
});
export const FaultConfig = IDL.Record({
  'id' : FaultId,
  'severityWeight' : IDL.Nat,
  'sequenceOrder' : IDL.Nat,
  'parameters' : IDL.Vec(FaultParameter),
  'durationSeconds' : IDL.Nat,
  'faultType' : IDL.Text,
});
export const ExperimentView = IDL.Record({
  'id' : ExperimentId,
  'status' : ExperimentStatus,
  'isTemplate' : IDL.Bool,
  'owner' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'hypothesis' : IDL.Text,
  'updatedAt' : Timestamp,
  'infrastructureTarget' : InfrastructureTarget,
  'probes' : IDL.Vec(ProbeConfig),
  'blastRadius' : BlastRadiusConfig,
  'faults' : IDL.Vec(FaultConfig),
});
export const ProbeResult = IDL.Record({
  'probeName' : IDL.Text,
  'message' : IDL.Text,
  'checkedAt' : Timestamp,
  'passed' : IDL.Bool,
  'probeId' : IDL.Nat,
});
export const MetricsSnapshot = IDL.Record({
  'probeResults' : IDL.Vec(ProbeResult),
  'affectedServiceCount' : IDL.Nat,
  'cpuUtilization' : IDL.Float64,
  'errorRate' : IDL.Float64,
  'latencyP50' : IDL.Float64,
  'latencyP95' : IDL.Float64,
  'latencyP99' : IDL.Float64,
  'memoryUtilization' : IDL.Float64,
});
export const ExperimentInput = IDL.Record({
  'isTemplate' : IDL.Bool,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'hypothesis' : IDL.Text,
  'infrastructureTarget' : InfrastructureTarget,
  'probes' : IDL.Vec(ProbeConfig),
  'blastRadius' : BlastRadiusConfig,
  'faults' : IDL.Vec(FaultConfig),
});
export const DateRangeFilter = IDL.Record({
  'toTs' : IDL.Opt(Timestamp),
  'fromTs' : IDL.Opt(Timestamp),
});
export const RecentRunSummary = IDL.Record({
  'status' : IDL.Text,
  'experimentId' : ExperimentId,
  'date' : Timestamp,
  'score' : IDL.Opt(IDL.Nat),
  'faultCount' : IDL.Nat,
  'probePassRate' : IDL.Float64,
  'runId' : RunId,
  'experimentName' : IDL.Text,
});
export const RunStatus = IDL.Variant({
  'stopped' : IDL.Null,
  'completed' : IDL.Null,
  'error' : IDL.Null,
  'queued' : IDL.Null,
  'running' : IDL.Null,
});
export const FaultRunStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'executing' : IDL.Null,
  'failed' : IDL.Null,
});
export const FaultResultView = IDL.Record({
  'status' : FaultRunStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'startedAt' : IDL.Opt(Timestamp),
  'affectedInstances' : IDL.Nat,
  'faultId' : FaultId,
});
export const ExecutionRunView = IDL.Record({
  'id' : RunId,
  'status' : RunStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'faultResults' : IDL.Vec(FaultResultView),
  'startedAt' : IDL.Opt(Timestamp),
  'metrics' : IDL.Opt(MetricsSnapshot),
  'experimentId' : ExperimentId,
  'actualDurationSeconds' : IDL.Nat,
  'resilienceScore' : IDL.Opt(IDL.Nat),
});
export const ServiceBreakdown = IDL.Record({
  'service' : IDL.Text,
  'failureCount' : IDL.Nat,
  'averageScore' : IDL.Nat,
});
export const InfraBreakdown = IDL.Record({
  'runCount' : IDL.Nat,
  'infrastructure' : IDL.Text,
  'averageScore' : IDL.Nat,
});
export const ScoreHistoryEntry = IDL.Record({
  'score' : IDL.Nat,
  'timestamp' : Timestamp,
  'runId' : RunId,
});
export const FailureMode = IDL.Record({
  'occurrenceCount' : IDL.Nat,
  'faultType' : IDL.Text,
  'averageSeverity' : IDL.Nat,
});
export const OrganizationStats = IDL.Record({
  'breakdownByService' : IDL.Vec(ServiceBreakdown),
  'breakdownByInfrastructure' : IDL.Vec(InfraBreakdown),
  'scoreHistory' : IDL.Vec(ScoreHistoryEntry),
  'currentScore' : IDL.Nat,
  'topFailureModes' : IDL.Vec(FailureMode),
});

export const idlService = IDL.Service({
  'addLogEntry' : IDL.Func(
      [RunId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [LogEntry],
      [],
    ),
  'cloneExperiment' : IDL.Func([ExperimentId], [IDL.Opt(ExperimentView)], []),
  'completeRun' : IDL.Func([RunId, MetricsSnapshot], [IDL.Bool], []),
  'createExperiment' : IDL.Func([ExperimentInput], [ExperimentView], []),
  'deleteExperiment' : IDL.Func([ExperimentId], [IDL.Bool], []),
  'emergencyStop' : IDL.Func([RunId], [IDL.Bool], []),
  'filterRuns' : IDL.Func(
      [DateRangeFilter, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(RecentRunSummary)],
      ['query'],
    ),
  'getExecutionRun' : IDL.Func([RunId], [IDL.Opt(ExecutionRunView)], ['query']),
  'getExperiment' : IDL.Func(
      [ExperimentId],
      [IDL.Opt(ExperimentView)],
      ['query'],
    ),
  'getOrganizationStats' : IDL.Func([], [OrganizationStats], ['query']),
  'getRecentRuns' : IDL.Func([IDL.Nat], [IDL.Vec(RecentRunSummary)], ['query']),
  'getRunLogs' : IDL.Func([RunId], [IDL.Vec(LogEntry)], ['query']),
  'getTopFailureModes' : IDL.Func([], [IDL.Vec(FailureMode)], ['query']),
  'listExperiments' : IDL.Func([], [IDL.Vec(ExperimentView)], ['query']),
  'listRunsByExperiment' : IDL.Func(
      [ExperimentId],
      [IDL.Vec(ExecutionRunView)],
      ['query'],
    ),
  'listTemplates' : IDL.Func([], [IDL.Vec(ExperimentView)], ['query']),
  'startExperiment' : IDL.Func([ExperimentId], [IDL.Opt(ExecutionRunView)], []),
  'updateExperiment' : IDL.Func(
      [ExperimentId, ExperimentInput],
      [IDL.Bool],
      [],
    ),
  'updateFaultResult' : IDL.Func(
      [RunId, FaultId, FaultRunStatus, IDL.Nat],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RunId = IDL.Nat;
  const Timestamp = IDL.Int;
  const LogEntry = IDL.Record({
    'id' : IDL.Nat,
    'result' : IDL.Text,
    'affectedTarget' : IDL.Text,
    'action' : IDL.Text,
    'timestamp' : Timestamp,
    'experimentRunId' : RunId,
    'faultType' : IDL.Text,
  });
  const ExperimentId = IDL.Nat;
  const ExperimentStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'stopped' : IDL.Null,
    'completed' : IDL.Null,
    'error' : IDL.Null,
    'draft' : IDL.Null,
    'running' : IDL.Null,
  });
  const InfrastructureTarget = IDL.Variant({
    'aws' : IDL.Null,
    'azure' : IDL.Null,
    'custom' : IDL.Null,
    'kubernetes' : IDL.Null,
    'linux' : IDL.Null,
  });
  const ProbeType = IDL.Variant({
    'metricThreshold' : IDL.Record({
      'threshold' : IDL.Float64,
      'operator' : IDL.Text,
      'metricName' : IDL.Text,
    }),
    'custom' : IDL.Record({ 'description' : IDL.Text, 'command' : IDL.Text }),
    'http' : IDL.Record({
      'url' : IDL.Text,
      'expectedStatusCode' : IDL.Nat,
      'timeoutSeconds' : IDL.Nat,
    }),
  });
  const ProbeConfig = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'probeType' : ProbeType,
  });
  const BlastRadiusConfig = IDL.Record({
    'autoRollback' : IDL.Bool,
    'trafficPercentage' : IDL.Nat,
    'instancePercentage' : IDL.Nat,
    'maxDurationSeconds' : IDL.Nat,
    'geographicScope' : IDL.Variant({
      'multi' : IDL.Null,
      'global' : IDL.Null,
      'single' : IDL.Null,
    }),
  });
  const FaultId = IDL.Nat;
  const FaultParameter = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const FaultConfig = IDL.Record({
    'id' : FaultId,
    'severityWeight' : IDL.Nat,
    'sequenceOrder' : IDL.Nat,
    'parameters' : IDL.Vec(FaultParameter),
    'durationSeconds' : IDL.Nat,
    'faultType' : IDL.Text,
  });
  const ExperimentView = IDL.Record({
    'id' : ExperimentId,
    'status' : ExperimentStatus,
    'isTemplate' : IDL.Bool,
    'owner' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'hypothesis' : IDL.Text,
    'updatedAt' : Timestamp,
    'infrastructureTarget' : InfrastructureTarget,
    'probes' : IDL.Vec(ProbeConfig),
    'blastRadius' : BlastRadiusConfig,
    'faults' : IDL.Vec(FaultConfig),
  });
  const ProbeResult = IDL.Record({
    'probeName' : IDL.Text,
    'message' : IDL.Text,
    'checkedAt' : Timestamp,
    'passed' : IDL.Bool,
    'probeId' : IDL.Nat,
  });
  const MetricsSnapshot = IDL.Record({
    'probeResults' : IDL.Vec(ProbeResult),
    'affectedServiceCount' : IDL.Nat,
    'cpuUtilization' : IDL.Float64,
    'errorRate' : IDL.Float64,
    'latencyP50' : IDL.Float64,
    'latencyP95' : IDL.Float64,
    'latencyP99' : IDL.Float64,
    'memoryUtilization' : IDL.Float64,
  });
  const ExperimentInput = IDL.Record({
    'isTemplate' : IDL.Bool,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'hypothesis' : IDL.Text,
    'infrastructureTarget' : InfrastructureTarget,
    'probes' : IDL.Vec(ProbeConfig),
    'blastRadius' : BlastRadiusConfig,
    'faults' : IDL.Vec(FaultConfig),
  });
  const DateRangeFilter = IDL.Record({
    'toTs' : IDL.Opt(Timestamp),
    'fromTs' : IDL.Opt(Timestamp),
  });
  const RecentRunSummary = IDL.Record({
    'status' : IDL.Text,
    'experimentId' : ExperimentId,
    'date' : Timestamp,
    'score' : IDL.Opt(IDL.Nat),
    'faultCount' : IDL.Nat,
    'probePassRate' : IDL.Float64,
    'runId' : RunId,
    'experimentName' : IDL.Text,
  });
  const RunStatus = IDL.Variant({
    'stopped' : IDL.Null,
    'completed' : IDL.Null,
    'error' : IDL.Null,
    'queued' : IDL.Null,
    'running' : IDL.Null,
  });
  const FaultRunStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'executing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const FaultResultView = IDL.Record({
    'status' : FaultRunStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'startedAt' : IDL.Opt(Timestamp),
    'affectedInstances' : IDL.Nat,
    'faultId' : FaultId,
  });
  const ExecutionRunView = IDL.Record({
    'id' : RunId,
    'status' : RunStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'faultResults' : IDL.Vec(FaultResultView),
    'startedAt' : IDL.Opt(Timestamp),
    'metrics' : IDL.Opt(MetricsSnapshot),
    'experimentId' : ExperimentId,
    'actualDurationSeconds' : IDL.Nat,
    'resilienceScore' : IDL.Opt(IDL.Nat),
  });
  const ServiceBreakdown = IDL.Record({
    'service' : IDL.Text,
    'failureCount' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  const InfraBreakdown = IDL.Record({
    'runCount' : IDL.Nat,
    'infrastructure' : IDL.Text,
    'averageScore' : IDL.Nat,
  });
  const ScoreHistoryEntry = IDL.Record({
    'score' : IDL.Nat,
    'timestamp' : Timestamp,
    'runId' : RunId,
  });
  const FailureMode = IDL.Record({
    'occurrenceCount' : IDL.Nat,
    'faultType' : IDL.Text,
    'averageSeverity' : IDL.Nat,
  });
  const OrganizationStats = IDL.Record({
    'breakdownByService' : IDL.Vec(ServiceBreakdown),
    'breakdownByInfrastructure' : IDL.Vec(InfraBreakdown),
    'scoreHistory' : IDL.Vec(ScoreHistoryEntry),
    'currentScore' : IDL.Nat,
    'topFailureModes' : IDL.Vec(FailureMode),
  });
  
  return IDL.Service({
    'addLogEntry' : IDL.Func(
        [RunId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [LogEntry],
        [],
      ),
    'cloneExperiment' : IDL.Func([ExperimentId], [IDL.Opt(ExperimentView)], []),
    'completeRun' : IDL.Func([RunId, MetricsSnapshot], [IDL.Bool], []),
    'createExperiment' : IDL.Func([ExperimentInput], [ExperimentView], []),
    'deleteExperiment' : IDL.Func([ExperimentId], [IDL.Bool], []),
    'emergencyStop' : IDL.Func([RunId], [IDL.Bool], []),
    'filterRuns' : IDL.Func(
        [DateRangeFilter, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(RecentRunSummary)],
        ['query'],
      ),
    'getExecutionRun' : IDL.Func(
        [RunId],
        [IDL.Opt(ExecutionRunView)],
        ['query'],
      ),
    'getExperiment' : IDL.Func(
        [ExperimentId],
        [IDL.Opt(ExperimentView)],
        ['query'],
      ),
    'getOrganizationStats' : IDL.Func([], [OrganizationStats], ['query']),
    'getRecentRuns' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(RecentRunSummary)],
        ['query'],
      ),
    'getRunLogs' : IDL.Func([RunId], [IDL.Vec(LogEntry)], ['query']),
    'getTopFailureModes' : IDL.Func([], [IDL.Vec(FailureMode)], ['query']),
    'listExperiments' : IDL.Func([], [IDL.Vec(ExperimentView)], ['query']),
    'listRunsByExperiment' : IDL.Func(
        [ExperimentId],
        [IDL.Vec(ExecutionRunView)],
        ['query'],
      ),
    'listTemplates' : IDL.Func([], [IDL.Vec(ExperimentView)], ['query']),
    'startExperiment' : IDL.Func(
        [ExperimentId],
        [IDL.Opt(ExecutionRunView)],
        [],
      ),
    'updateExperiment' : IDL.Func(
        [ExperimentId, ExperimentInput],
        [IDL.Bool],
        [],
      ),
    'updateFaultResult' : IDL.Func(
        [RunId, FaultId, FaultRunStatus, IDL.Nat],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };