/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BlastRadiusConfig {
    autoRollback: boolean;
    trafficPercentage: bigint;
    instancePercentage: bigint;
    maxDurationSeconds: bigint;
    geographicScope: Variant_multi_global_single;
}
export interface ScoreHistoryEntry {
    score: bigint;
    timestamp: Timestamp;
    runId: RunId;
}
export type Timestamp = bigint;
export interface MetricsSnapshot {
    probeResults: Array<ProbeResult>;
    affectedServiceCount: bigint;
    cpuUtilization: number;
    errorRate: number;
    latencyP50: number;
    latencyP95: number;
    latencyP99: number;
    memoryUtilization: number;
}
export type ProbeType = {
    __kind__: "metricThreshold";
    metricThreshold: {
        threshold: number;
        operator: string;
        metricName: string;
    };
} | {
    __kind__: "custom";
    custom: {
        description: string;
        command: string;
    };
} | {
    __kind__: "http";
    http: {
        url: string;
        expectedStatusCode: bigint;
        timeoutSeconds: bigint;
    };
};
export interface ProbeResult {
    probeName: string;
    message: string;
    checkedAt: Timestamp;
    passed: boolean;
    probeId: bigint;
}
export interface OrganizationStats {
    breakdownByService: Array<ServiceBreakdown>;
    breakdownByInfrastructure: Array<InfraBreakdown>;
    scoreHistory: Array<ScoreHistoryEntry>;
    currentScore: bigint;
    topFailureModes: Array<FailureMode>;
}
export interface InfraBreakdown {
    runCount: bigint;
    infrastructure: string;
    averageScore: bigint;
}
export interface FaultResultView {
    status: FaultRunStatus;
    completedAt?: Timestamp;
    startedAt?: Timestamp;
    affectedInstances: bigint;
    faultId: FaultId;
}
export type FaultId = bigint;
export interface ProbeConfig {
    id: bigint;
    name: string;
    probeType: ProbeType;
}
export interface ExperimentView {
    id: ExperimentId;
    status: ExperimentStatus;
    isTemplate: boolean;
    owner: string;
    name: string;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    hypothesis: string;
    updatedAt: Timestamp;
    infrastructureTarget: InfrastructureTarget;
    probes: Array<ProbeConfig>;
    blastRadius: BlastRadiusConfig;
    faults: Array<FaultConfig>;
}
export interface ExperimentInput {
    isTemplate: boolean;
    name: string;
    tags: Array<string>;
    description: string;
    hypothesis: string;
    infrastructureTarget: InfrastructureTarget;
    probes: Array<ProbeConfig>;
    blastRadius: BlastRadiusConfig;
    faults: Array<FaultConfig>;
}
export interface FaultConfig {
    id: FaultId;
    severityWeight: bigint;
    sequenceOrder: bigint;
    parameters: Array<FaultParameter>;
    durationSeconds: bigint;
    faultType: string;
}
export interface ExecutionRunView {
    id: RunId;
    status: RunStatus;
    completedAt?: Timestamp;
    faultResults: Array<FaultResultView>;
    startedAt?: Timestamp;
    metrics?: MetricsSnapshot;
    experimentId: ExperimentId;
    actualDurationSeconds: bigint;
    resilienceScore?: bigint;
}
export interface ServiceBreakdown {
    service: string;
    failureCount: bigint;
    averageScore: bigint;
}
export interface LogEntry {
    id: bigint;
    result: string;
    affectedTarget: string;
    action: string;
    timestamp: Timestamp;
    experimentRunId: RunId;
    faultType: string;
}
export type ExperimentId = bigint;
export interface DateRangeFilter {
    toTs?: Timestamp;
    fromTs?: Timestamp;
}
export type RunId = bigint;
export interface FailureMode {
    occurrenceCount: bigint;
    faultType: string;
    averageSeverity: bigint;
}
export interface RecentRunSummary {
    status: string;
    experimentId: ExperimentId;
    date: Timestamp;
    score?: bigint;
    faultCount: bigint;
    probePassRate: number;
    runId: RunId;
    experimentName: string;
}
export interface FaultParameter {
    key: string;
    value: string;
}
export enum ExperimentStatus {
    scheduled = "scheduled",
    stopped = "stopped",
    completed = "completed",
    error = "error",
    draft = "draft",
    running = "running"
}
export enum FaultRunStatus {
    pending = "pending",
    completed = "completed",
    executing = "executing",
    failed = "failed"
}
export enum InfrastructureTarget {
    aws = "aws",
    azure = "azure",
    custom = "custom",
    kubernetes = "kubernetes",
    linux = "linux"
}
export enum RunStatus {
    stopped = "stopped",
    completed = "completed",
    error = "error",
    queued = "queued",
    running = "running"
}
export enum Variant_multi_global_single {
    multi = "multi",
    global = "global",
    single = "single"
}
export interface backendInterface {
    addLogEntry(runId: RunId, faultType: string, action: string, result: string, affectedTarget: string): Promise<LogEntry>;
    cloneExperiment(sourceId: ExperimentId): Promise<ExperimentView | null>;
    completeRun(runId: RunId, metrics: MetricsSnapshot): Promise<boolean>;
    createExperiment(input: ExperimentInput): Promise<ExperimentView>;
    deleteExperiment(id: ExperimentId): Promise<boolean>;
    emergencyStop(runId: RunId): Promise<boolean>;
    filterRuns(dateRange: DateRangeFilter, infrastructure: string | null, service: string | null): Promise<Array<RecentRunSummary>>;
    getExecutionRun(id: RunId): Promise<ExecutionRunView | null>;
    getExperiment(id: ExperimentId): Promise<ExperimentView | null>;
    getOrganizationStats(): Promise<OrganizationStats>;
    getRecentRuns(limit: bigint): Promise<Array<RecentRunSummary>>;
    getRunLogs(runId: RunId): Promise<Array<LogEntry>>;
    getTopFailureModes(): Promise<Array<FailureMode>>;
    listExperiments(): Promise<Array<ExperimentView>>;
    listRunsByExperiment(experimentId: ExperimentId): Promise<Array<ExecutionRunView>>;
    listTemplates(): Promise<Array<ExperimentView>>;
    startExperiment(experimentId: ExperimentId): Promise<ExecutionRunView | null>;
    updateExperiment(id: ExperimentId, input: ExperimentInput): Promise<boolean>;
    updateFaultResult(runId: RunId, faultId: FaultId, status: FaultRunStatus, affectedInstances: bigint): Promise<boolean>;
}
import type { BlastRadiusConfig as _BlastRadiusConfig, DateRangeFilter as _DateRangeFilter, ExecutionRunView as _ExecutionRunView, ExperimentId as _ExperimentId, ExperimentInput as _ExperimentInput, ExperimentStatus as _ExperimentStatus, ExperimentView as _ExperimentView, FaultConfig as _FaultConfig, FaultId as _FaultId, FaultResultView as _FaultResultView, FaultRunStatus as _FaultRunStatus, InfrastructureTarget as _InfrastructureTarget, MetricsSnapshot as _MetricsSnapshot, ProbeConfig as _ProbeConfig, ProbeType as _ProbeType, RecentRunSummary as _RecentRunSummary, RunId as _RunId, RunStatus as _RunStatus, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addLogEntry(arg0: RunId, arg1: string, arg2: string, arg3: string, arg4: string): Promise<LogEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addLogEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLogEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async cloneExperiment(arg0: ExperimentId): Promise<ExperimentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.cloneExperiment(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cloneExperiment(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeRun(arg0: RunId, arg1: MetricsSnapshot): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeRun(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeRun(arg0, arg1);
            return result;
        }
    }
    async createExperiment(arg0: ExperimentInput): Promise<ExperimentView> {
        if (this.processError) {
            try {
                const result = await this.actor.createExperiment(to_candid_ExperimentInput_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ExperimentView_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExperiment(to_candid_ExperimentInput_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ExperimentView_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteExperiment(arg0: ExperimentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExperiment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExperiment(arg0);
            return result;
        }
    }
    async emergencyStop(arg0: RunId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.emergencyStop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.emergencyStop(arg0);
            return result;
        }
    }
    async filterRuns(arg0: DateRangeFilter, arg1: string | null, arg2: string | null): Promise<Array<RecentRunSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterRuns(to_candid_DateRangeFilter_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterRuns(to_candid_DateRangeFilter_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExecutionRun(arg0: RunId): Promise<ExecutionRunView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExecutionRun(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExecutionRun(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExperiment(arg0: ExperimentId): Promise<ExperimentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExperiment(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExperiment(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrganizationStats(): Promise<OrganizationStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrganizationStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrganizationStats();
            return result;
        }
    }
    async getRecentRuns(arg0: bigint): Promise<Array<RecentRunSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentRuns(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentRuns(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRunLogs(arg0: RunId): Promise<Array<LogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRunLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRunLogs(arg0);
            return result;
        }
    }
    async getTopFailureModes(): Promise<Array<FailureMode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopFailureModes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopFailureModes();
            return result;
        }
    }
    async listExperiments(): Promise<Array<ExperimentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExperiments();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExperiments();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRunsByExperiment(arg0: ExperimentId): Promise<Array<ExecutionRunView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRunsByExperiment(arg0);
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRunsByExperiment(arg0);
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTemplates(): Promise<Array<ExperimentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTemplates();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTemplates();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async startExperiment(arg0: ExperimentId): Promise<ExecutionRunView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.startExperiment(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startExperiment(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateExperiment(arg0: ExperimentId, arg1: ExperimentInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExperiment(arg0, to_candid_ExperimentInput_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExperiment(arg0, to_candid_ExperimentInput_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateFaultResult(arg0: RunId, arg1: FaultId, arg2: FaultRunStatus, arg3: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFaultResult(arg0, arg1, to_candid_FaultRunStatus_n49(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFaultResult(arg0, arg1, to_candid_FaultRunStatus_n49(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
}
function from_candid_BlastRadiusConfig_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlastRadiusConfig): BlastRadiusConfig {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ExecutionRunView_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExecutionRunView): ExecutionRunView {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_ExperimentStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExperimentStatus): ExperimentStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ExperimentView_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExperimentView): ExperimentView {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_FaultResultView_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FaultResultView): FaultResultView {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_FaultRunStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FaultRunStatus): FaultRunStatus {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_InfrastructureTarget_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InfrastructureTarget): InfrastructureTarget {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ProbeConfig_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProbeConfig): ProbeConfig {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ProbeType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProbeType): ProbeType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_RecentRunSummary_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecentRunSummary): RecentRunSummary {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_RunStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RunStatus): RunStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExperimentView]): ExperimentView | null {
    return value.length === 0 ? null : from_candid_ExperimentView_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExecutionRunView]): ExecutionRunView | null {
    return value.length === 0 ? null : from_candid_ExecutionRunView_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MetricsSnapshot]): MetricsSnapshot | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    probeType: _ProbeType;
}): {
    id: bigint;
    name: string;
    probeType: ProbeType;
} {
    return {
        id: value.id,
        name: value.name,
        probeType: from_candid_ProbeType_n11(_uploadFile, _downloadFile, value.probeType)
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    autoRollback: boolean;
    trafficPercentage: bigint;
    instancePercentage: bigint;
    maxDurationSeconds: bigint;
    geographicScope: {
        multi: null;
    } | {
        global: null;
    } | {
        single: null;
    };
}): {
    autoRollback: boolean;
    trafficPercentage: bigint;
    instancePercentage: bigint;
    maxDurationSeconds: bigint;
    geographicScope: Variant_multi_global_single;
} {
    return {
        autoRollback: value.autoRollback,
        trafficPercentage: value.trafficPercentage,
        instancePercentage: value.instancePercentage,
        maxDurationSeconds: value.maxDurationSeconds,
        geographicScope: from_candid_variant_n15(_uploadFile, _downloadFile, value.geographicScope)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ExperimentId;
    status: _ExperimentStatus;
    isTemplate: boolean;
    owner: string;
    name: string;
    createdAt: _Timestamp;
    tags: Array<string>;
    description: string;
    hypothesis: string;
    updatedAt: _Timestamp;
    infrastructureTarget: _InfrastructureTarget;
    probes: Array<_ProbeConfig>;
    blastRadius: _BlastRadiusConfig;
    faults: Array<_FaultConfig>;
}): {
    id: ExperimentId;
    status: ExperimentStatus;
    isTemplate: boolean;
    owner: string;
    name: string;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    hypothesis: string;
    updatedAt: Timestamp;
    infrastructureTarget: InfrastructureTarget;
    probes: Array<ProbeConfig>;
    blastRadius: BlastRadiusConfig;
    faults: Array<FaultConfig>;
} {
    return {
        id: value.id,
        status: from_candid_ExperimentStatus_n4(_uploadFile, _downloadFile, value.status),
        isTemplate: value.isTemplate,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        hypothesis: value.hypothesis,
        updatedAt: value.updatedAt,
        infrastructureTarget: from_candid_InfrastructureTarget_n6(_uploadFile, _downloadFile, value.infrastructureTarget),
        probes: from_candid_vec_n8(_uploadFile, _downloadFile, value.probes),
        blastRadius: from_candid_BlastRadiusConfig_n13(_uploadFile, _downloadFile, value.blastRadius),
        faults: value.faults
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    experimentId: _ExperimentId;
    date: _Timestamp;
    score: [] | [bigint];
    faultCount: bigint;
    probePassRate: number;
    runId: _RunId;
    experimentName: string;
}): {
    status: string;
    experimentId: ExperimentId;
    date: Timestamp;
    score?: bigint;
    faultCount: bigint;
    probePassRate: number;
    runId: RunId;
    experimentName: string;
} {
    return {
        status: value.status,
        experimentId: value.experimentId,
        date: value.date,
        score: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.score)),
        faultCount: value.faultCount,
        probePassRate: value.probePassRate,
        runId: value.runId,
        experimentName: value.experimentName
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RunId;
    status: _RunStatus;
    completedAt: [] | [_Timestamp];
    faultResults: Array<_FaultResultView>;
    startedAt: [] | [_Timestamp];
    metrics: [] | [_MetricsSnapshot];
    experimentId: _ExperimentId;
    actualDurationSeconds: bigint;
    resilienceScore: [] | [bigint];
}): {
    id: RunId;
    status: RunStatus;
    completedAt?: Timestamp;
    faultResults: Array<FaultResultView>;
    startedAt?: Timestamp;
    metrics?: MetricsSnapshot;
    experimentId: ExperimentId;
    actualDurationSeconds: bigint;
    resilienceScore?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_RunStatus_n38(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.completedAt)),
        faultResults: from_candid_vec_n41(_uploadFile, _downloadFile, value.faultResults),
        startedAt: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.startedAt)),
        metrics: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.metrics)),
        experimentId: value.experimentId,
        actualDurationSeconds: value.actualDurationSeconds,
        resilienceScore: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.resilienceScore))
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _FaultRunStatus;
    completedAt: [] | [_Timestamp];
    startedAt: [] | [_Timestamp];
    affectedInstances: bigint;
    faultId: _FaultId;
}): {
    status: FaultRunStatus;
    completedAt?: Timestamp;
    startedAt?: Timestamp;
    affectedInstances: bigint;
    faultId: FaultId;
} {
    return {
        status: from_candid_FaultRunStatus_n44(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.completedAt)),
        startedAt: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.startedAt)),
        affectedInstances: value.affectedInstances,
        faultId: value.faultId
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metricThreshold: {
        threshold: number;
        operator: string;
        metricName: string;
    };
} | {
    custom: {
        description: string;
        command: string;
    };
} | {
    http: {
        url: string;
        expectedStatusCode: bigint;
        timeoutSeconds: bigint;
    };
}): {
    __kind__: "metricThreshold";
    metricThreshold: {
        threshold: number;
        operator: string;
        metricName: string;
    };
} | {
    __kind__: "custom";
    custom: {
        description: string;
        command: string;
    };
} | {
    __kind__: "http";
    http: {
        url: string;
        expectedStatusCode: bigint;
        timeoutSeconds: bigint;
    };
} {
    return "metricThreshold" in value ? {
        __kind__: "metricThreshold",
        metricThreshold: value.metricThreshold
    } : "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : "http" in value ? {
        __kind__: "http",
        http: value.http
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    multi: null;
} | {
    global: null;
} | {
    single: null;
}): Variant_multi_global_single {
    return "multi" in value ? Variant_multi_global_single.multi : "global" in value ? Variant_multi_global_single.global : "single" in value ? Variant_multi_global_single.single : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stopped: null;
} | {
    completed: null;
} | {
    error: null;
} | {
    queued: null;
} | {
    running: null;
}): RunStatus {
    return "stopped" in value ? RunStatus.stopped : "completed" in value ? RunStatus.completed : "error" in value ? RunStatus.error : "queued" in value ? RunStatus.queued : "running" in value ? RunStatus.running : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    executing: null;
} | {
    failed: null;
}): FaultRunStatus {
    return "pending" in value ? FaultRunStatus.pending : "completed" in value ? FaultRunStatus.completed : "executing" in value ? FaultRunStatus.executing : "failed" in value ? FaultRunStatus.failed : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    stopped: null;
} | {
    completed: null;
} | {
    error: null;
} | {
    draft: null;
} | {
    running: null;
}): ExperimentStatus {
    return "scheduled" in value ? ExperimentStatus.scheduled : "stopped" in value ? ExperimentStatus.stopped : "completed" in value ? ExperimentStatus.completed : "error" in value ? ExperimentStatus.error : "draft" in value ? ExperimentStatus.draft : "running" in value ? ExperimentStatus.running : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aws: null;
} | {
    azure: null;
} | {
    custom: null;
} | {
    kubernetes: null;
} | {
    linux: null;
}): InfrastructureTarget {
    return "aws" in value ? InfrastructureTarget.aws : "azure" in value ? InfrastructureTarget.azure : "custom" in value ? InfrastructureTarget.custom : "kubernetes" in value ? InfrastructureTarget.kubernetes : "linux" in value ? InfrastructureTarget.linux : value;
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecentRunSummary>): Array<RecentRunSummary> {
    return value.map((x)=>from_candid_RecentRunSummary_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FaultResultView>): Array<FaultResultView> {
    return value.map((x)=>from_candid_FaultResultView_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExperimentView>): Array<ExperimentView> {
    return value.map((x)=>from_candid_ExperimentView_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExecutionRunView>): Array<ExecutionRunView> {
    return value.map((x)=>from_candid_ExecutionRunView_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProbeConfig>): Array<ProbeConfig> {
    return value.map((x)=>from_candid_ProbeConfig_n9(_uploadFile, _downloadFile, x));
}
function to_candid_BlastRadiusConfig_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlastRadiusConfig): _BlastRadiusConfig {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_DateRangeFilter_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DateRangeFilter): _DateRangeFilter {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_ExperimentInput_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperimentInput): _ExperimentInput {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_FaultRunStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FaultRunStatus): _FaultRunStatus {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_InfrastructureTarget_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InfrastructureTarget): _InfrastructureTarget {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_ProbeConfig_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProbeConfig): _ProbeConfig {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_ProbeType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProbeType): _ProbeType {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isTemplate: boolean;
    name: string;
    tags: Array<string>;
    description: string;
    hypothesis: string;
    infrastructureTarget: InfrastructureTarget;
    probes: Array<ProbeConfig>;
    blastRadius: BlastRadiusConfig;
    faults: Array<FaultConfig>;
}): {
    isTemplate: boolean;
    name: string;
    tags: Array<string>;
    description: string;
    hypothesis: string;
    infrastructureTarget: _InfrastructureTarget;
    probes: Array<_ProbeConfig>;
    blastRadius: _BlastRadiusConfig;
    faults: Array<_FaultConfig>;
} {
    return {
        isTemplate: value.isTemplate,
        name: value.name,
        tags: value.tags,
        description: value.description,
        hypothesis: value.hypothesis,
        infrastructureTarget: to_candid_InfrastructureTarget_n18(_uploadFile, _downloadFile, value.infrastructureTarget),
        probes: to_candid_vec_n20(_uploadFile, _downloadFile, value.probes),
        blastRadius: to_candid_BlastRadiusConfig_n25(_uploadFile, _downloadFile, value.blastRadius),
        faults: value.faults
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    probeType: ProbeType;
}): {
    id: bigint;
    name: string;
    probeType: _ProbeType;
} {
    return {
        id: value.id,
        name: value.name,
        probeType: to_candid_ProbeType_n23(_uploadFile, _downloadFile, value.probeType)
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    autoRollback: boolean;
    trafficPercentage: bigint;
    instancePercentage: bigint;
    maxDurationSeconds: bigint;
    geographicScope: Variant_multi_global_single;
}): {
    autoRollback: boolean;
    trafficPercentage: bigint;
    instancePercentage: bigint;
    maxDurationSeconds: bigint;
    geographicScope: {
        multi: null;
    } | {
        global: null;
    } | {
        single: null;
    };
} {
    return {
        autoRollback: value.autoRollback,
        trafficPercentage: value.trafficPercentage,
        instancePercentage: value.instancePercentage,
        maxDurationSeconds: value.maxDurationSeconds,
        geographicScope: to_candid_variant_n27(_uploadFile, _downloadFile, value.geographicScope)
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    toTs?: Timestamp;
    fromTs?: Timestamp;
}): {
    toTs: [] | [_Timestamp];
    fromTs: [] | [_Timestamp];
} {
    return {
        toTs: value.toTs ? candid_some(value.toTs) : candid_none(),
        fromTs: value.fromTs ? candid_some(value.fromTs) : candid_none()
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InfrastructureTarget): {
    aws: null;
} | {
    azure: null;
} | {
    custom: null;
} | {
    kubernetes: null;
} | {
    linux: null;
} {
    return value == InfrastructureTarget.aws ? {
        aws: null
    } : value == InfrastructureTarget.azure ? {
        azure: null
    } : value == InfrastructureTarget.custom ? {
        custom: null
    } : value == InfrastructureTarget.kubernetes ? {
        kubernetes: null
    } : value == InfrastructureTarget.linux ? {
        linux: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "metricThreshold";
    metricThreshold: {
        threshold: number;
        operator: string;
        metricName: string;
    };
} | {
    __kind__: "custom";
    custom: {
        description: string;
        command: string;
    };
} | {
    __kind__: "http";
    http: {
        url: string;
        expectedStatusCode: bigint;
        timeoutSeconds: bigint;
    };
}): {
    metricThreshold: {
        threshold: number;
        operator: string;
        metricName: string;
    };
} | {
    custom: {
        description: string;
        command: string;
    };
} | {
    http: {
        url: string;
        expectedStatusCode: bigint;
        timeoutSeconds: bigint;
    };
} {
    return value.__kind__ === "metricThreshold" ? {
        metricThreshold: value.metricThreshold
    } : value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "http" ? {
        http: value.http
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_multi_global_single): {
    multi: null;
} | {
    global: null;
} | {
    single: null;
} {
    return value == Variant_multi_global_single.multi ? {
        multi: null
    } : value == Variant_multi_global_single.global ? {
        global: null
    } : value == Variant_multi_global_single.single ? {
        single: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FaultRunStatus): {
    pending: null;
} | {
    completed: null;
} | {
    executing: null;
} | {
    failed: null;
} {
    return value == FaultRunStatus.pending ? {
        pending: null
    } : value == FaultRunStatus.completed ? {
        completed: null
    } : value == FaultRunStatus.executing ? {
        executing: null
    } : value == FaultRunStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ProbeConfig>): Array<_ProbeConfig> {
    return value.map((x)=>to_candid_ProbeConfig_n21(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
